version: '3.8'

services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin

  grinksync:
    build:
      context: ./grinksync
      dockerfile: Dockerfile
    container_name: grinksync
    depends_on:
      - grafana
    volumes:
      - grafana_data:/var/lib/grafana
    # environment:
    #   # Add any environment variables your grinksync container needs
    #   - SOME_ENV_VAR=value

volumes:
  grafana_data:
